# Generated by Django 5.1.15 on 2026-10-05 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_alter_contact_phone'),
        ('email_templates', '0002_templateimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('contact_added', 'Contact added to a list'), ('signup_form_submitted', 'Signup form submitted'), ('cart_abandoned', 'Cart abandoned (external event)')], max_length=40)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=64)),
                ('allow_reenrollment', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('current_step_order', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='automations.automation')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_enrollments', to='contacts.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('send_email', 'Send email'), ('wait', 'Wait'), ('end_automation', 'End automation')], default='send_email', max_length=30)),
                ('delay_value', models.PositiveIntegerField(default=0)),
                ('delay_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='days', max_length=10)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automations.automation')),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_steps', to='email_templates.emailtemplate')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveIntegerField()),
                ('action_type', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automation')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to='contacts.contact')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automationenrollment')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='automations.automationstep')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['owner', 'status'], name='automations_owner_i_2cb35a_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['status', 'trigger_type'], name='automations_status_9fd810_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automation',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='automationenrollment',
            index=models.Index(fields=['status', 'next_run_at'], name='automations_status_e4dfc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'paused'])), fields=('automation', 'contact'), name='uniq_live_enrollment_per_contact'),
        ),
        migrations.AlterUniqueTogether(
            name='automationstep',
            unique_together={('automation', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['automation', 'status'], name='automations_automat_a65506_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationexecution',
            constraint=models.UniqueConstraint(fields=('enrollment', 'step_order', 'attempt'), name='uniq_execution_attempt'),
        ),
    ]
