# Generated by Django 5.1.15 on 2026-09-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_tag_contact_tags_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
