# Generated by Django 5.1.15 on 2026-09-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('email_templates', '0002_templateimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('A', 'Version A'), ('B', 'Version B')], max_length=1)),
                ('subject', models.CharField(max_length=255)),
                ('split_percentage', models.PositiveSmallIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_variants', to='campaigns.campaign')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ab_variants', to='email_templates.emailtemplate')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('campaign', 'label')},
            },
        ),
    ]
