# Generated by Django 6.1 on 2026-08-31 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('soft_bounce', 'Soft bounce'), ('hard_bounce', 'Hard bounce'), ('blocked', 'Blocked'), ('spam', 'Spam complaint'), ('unsubscribed', 'Unsubscribed')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_events', to='contacts.contact')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.campaignrecipient')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['campaign', 'event_type'], name='analytics_c_campaig_4a5778_idx'), models.Index(fields=['contact', 'event_type'], name='analytics_c_contact_f7946b_idx')],
            },
        ),
    ]
