# Generated by Django 5.1.15 on 2026-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='event_type',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('soft_bounce', 'Soft bounce'), ('hard_bounce', 'Hard bounce'), ('blocked', 'Blocked'), ('spam', 'Spam complaint'), ('unsubscribed', 'Unsubscribed'), ('unsubscribe_viewed', 'Unsubscribe link viewed')], max_length=20),
        ),
    ]
