# Generated by Django 5.1.15 on 2026-09-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ab_testing', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('normal', 'Normal Campaign'), ('ab_test', 'A/B Test Campaign')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='ab_testing.campaignvariant'),
        ),
    ]
