# Generated by Django 5.1.15 on 2026-09-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('contacts', '0002_tag_contact_tags_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='contacts.segment'),
        ),
    ]
