# Generated by Django 5.1.15 on 2026-09-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_campaign_type_campaignrecipient_variant'),
        ('campaigns', '0002_campaign_segments'),
    ]

    operations = [
    ]
