# Generated by Django 6.1 on 2026-08-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledcampaign',
            name='celery_task_id',
        ),
    ]